---
- name: Create Pool
  hosts: f5
  connection: local
  tasks:
      - name: Create pool
        bigip_pool: 
            lb_method: ratio-member
            name: web1
            user: admin
            password: vangadi
            server: 192.168.78.128
            slow_ramp_time: 120
            validate_certs: no
        delegate_to: localhost
